[server]
maxUploadSize = 100
enableXsrfProtection = true
enableCORS = false
headless = true

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2F4BFF"
backgroundColor = "#EEF2F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#16222E"
font = "sans serif"
